name: Java CI with Gradle

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup missing gradle properties
        run: mkdir ~/.gradle && touch ~/.gradle/gradle.properties && echo "github.token=${{ secrets.GITHUB_TOKEN }}" > ~/.gradle/gradle.properties && echo "github.username=${{ github.repository.owner }}" > ~/.gradle/gradle.properties
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew assemble
